apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  labels:
    rbac.authorization.k8s.io/aggregate-to-test-admin: "true"
  name: admin
